#!/usr/bin/env bash

# ARG_HELP([GIM - Godot Install Manager\nManage multiple Godot editor versions.\n])
# ARG_VERSION([echo "$NAME_SHORT $VERSION"])
# ARG_OPTIONAL_ACTION([list],[l],[Lists all local Godot editor versions],[list_installed_editors])
# ARG_OPTIONAL_SINGLE([run],[r],[Launch a specific Godot editor if a version is passed, otherwise runs the latest present. Fails if no editors are present],[run_default_editor])
# ARG_OPTIONAL_SINGLE([install],[i],[Install a specific Godot editor version])
# ARGBASH_PREPARE()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.11.0 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.dev for more info


die()
{
	local _ret="${2:-1}"
	test "${_PRINT_HELP:-no}" = yes && print_help >&2
	echo "$1" >&2
	exit "${_ret}"
}


begins_with_short_option()
{
	local first_option all_short_options='hvlri'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_run="run_default_editor"
_arg_install=


print_help()
{
	printf '%s\n' "GIM - Godot Install Manager
Manage multiple Godot editor versions.
"
	printf 'Usage: %s [-h|--help] [-v|--version] [-l|--list] [-r|--run <arg>] [-i|--install <arg>]\n' "$0"
	printf '\t%s\n' "-h, --help: Prints help"
	printf '\t%s\n' "-v, --version: Prints version"
	printf '\t%s\n' "-l, --list: Lists all local Godot editor versions"
	printf '\t%s\n' "-r, --run: Launch a specific Godot editor if a version is passed, otherwise runs the latest present. Fails if no editors are present (default: 'run_default_editor')"
	printf '\t%s\n' "-i, --install: Install a specific Godot editor version (no default)"
}


parse_commandline()
{
	local _key
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			-v|--version)
				echo "$NAME_SHORT $VERSION"
				exit 0
				;;
			-v*)
				echo "$NAME_SHORT $VERSION"
				exit 0
				;;
			-l|--list)
				list_installed_editors
				exit 0
				;;
			-l*)
				list_installed_editors
				exit 0
				;;
			-r|--run)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_run="$2"
				shift
				;;
			--run=*)
				_arg_run="${_key##--run=}"
				;;
			-r*)
				_arg_run="${_key##-r}"
				;;
			-i|--install)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_install="$2"
				shift
				;;
			--install=*)
				_arg_install="${_key##--install=}"
				;;
			-i*)
				_arg_install="${_key##-i}"
				;;
			*)
				_PRINT_HELP=yes die "FATAL ERROR: Got an unexpected argument '$1'" 1
				;;
		esac
		shift
	done
}


# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


# --- Constants ---
NAME_SHORT="GIM"
NAME_LONG="Godot Installation Manager"
VERSION="0.1.0"

# --- XDG Base Directory Setup ---
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"

APP_CONFIG_DIR="$XDG_CONFIG_HOME/gim"
APP_DATA_DIR="$XDG_DATA_HOME/gim"
editors_dir="$APP_DATA_DIR/editors/"
editor_file_name_start="Godot"

DEFAULT_EDITOR_FILE="$APP_CONFIG_DIR/default_editor"

# --- Helper Functions ---

find_installed_editors() {
  installed_editors=()
  if [ ! -d "$editors_dir" ]; then
    return
  fi
  while IFS= read -r file; do
    if [ -x "$file" ]; then
      version=$("$file" --version 2>/dev/null)
      if [ -n "$version" ]; then
        installed_editors+=("$version")
      fi
    fi
  done < <(find "$editors_dir" -maxdepth 1 -type f -iname "${editor_file_name_start}*" 2>/dev/null)
}

find_editor_by_version() {
  local search_version="$1"
  local editor_path=""

  while IFS= read -r file; do
    if [ -x "$file" ]; then
      version=$("$file" --version 2>/dev/null)
      if [ -n "$version" ] && echo "$version" | grep -qF "$search_version"; then
        editor_path="$file"
        break
      fi
    fi
  done < <(find "$editors_dir" -maxdepth 1 -type f -iname "${editor_file_name_start}*" 2>/dev/null)

  if [ -z "$editor_path" ]; then
    echo "Error: No editor found matching version '$search_version' in $editors_dir" >&2
    return 1
  fi

  echo "$editor_path"
}

list_installed_editors() {
  find_installed_editors

  if [ ${#installed_editors[@]} -eq 0 ]; then
    echo "No Godot editors found in $editors_dir"
    echo "Place Godot editors inside this folder to start using $NAME_SHORT."
    exit 0
  fi
  # echo "Installed editors:"
  for editor in "${installed_editors[@]}"; do
    echo "  $editor"
  done
}


# --- Parse Arguments (after helper functions are defined) ---
parse_commandline "$@"

# --- Argument Handling ---

if [ "$_arg_list" = on ]; then
  find_installed_editors
  if [ ${#installed_editors[@]} -eq 0 ]; then
    echo "No Godot editors found in $editors_dir"
    echo "Place Godot editors inside this folder to start using $NAME_SHORT."
    exit 0
  fi
  echo "Installed editors:"
  for editor in "${installed_editors[@]}"; do
    echo "  $editor"
  done

else
  echo "$NAME_SHORT - $NAME_LONG"
  echo "Use -h or --help for usage information."
fi

# ] <-- needed because of Argbash
